package com.viktor.booking.api.dto;

public enum ApiErrorCode {

    USER_NOT_FOUND,
    SERVICE_NOT_FOUND,
    RESOURCE_NOT_FOUND,

    INVALID_CREDENTIALS,
    AUTHENTICATION_REQUIRED,
    ACCESS_DENIED,
    BOOKING_OPERATION_FORBIDDEN,

    VALIDATION_FAILED,
    INVALID_PARAMETER,
    MALFORMED_REQUEST,
    BOOKING_IN_PAST,
    INVALID_BOOKING_TIME,
    INVALID_BOOKING_DURATION,
    INVALID_BOOKING_SEARCH,

    BOOKING_TIME_CONFLICT,
    SERVICE_INACTIVE,
    BOOKING_CANNOT_BE_CANCELLED,
    BOOKING_CANNOT_BE_CONFIRMED,
    BOOKING_CANNOT_BE_DELETED,
    BOOKING_CANNOT_BE_RESCHEDULED,
    USER_ALREADY_EXISTS,

    INTERNAL_ERROR
}
